# Generated by Django 4.1.1 on 2023-08-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("purpose", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=100)),
                ("amount", models.IntegerField(default=0)),
                ("is_income", models.BooleanField(default=False)),
                ("is_debt", models.BooleanField(default=False)),
                ("is_weekly", models.BooleanField(default=True)),
                ("is_monthly", models.BooleanField(default=False)),
                ("debt_amount", models.IntegerField(default=0)),
                ("date", models.DateField()),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
        migrations.CreateModel(
            name="RecordsBackup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("records", models.CharField(max_length=100000)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Back-Up",
                "verbose_name_plural": "Back-Ups",
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("attendance_data", models.JSONField()),
                ("date", models.DateField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "The Register",
                "verbose_name_plural": "Registries",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "lessons_remaining_grammar_only",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "lessons_remaining_native_only",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "lessons_remaining",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("time", models.TimeField()),
                ("day", models.CharField(max_length=10)),
                ("isonline", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
    ]
