# Generated by Django 4.1.1 on 2023-09-06 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuttingBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.TimeField(auto_now_add=True)),
                ("strain", models.CharField(max_length=25)),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.TimeField(auto_now_add=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("hm", "home"),
                            ("fd", "food"),
                            ("bl", "bills"),
                            ("db", "debt"),
                            ("cr", "car"),
                            ("dg", "dogs"),
                            ("wf", "wife"),
                            ("hs", "husband"),
                            ("tl", "tutorland"),
                            ("cj", "CJgrower"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.CharField(max_length=30)),
                ("is_monthly", models.BooleanField(default=False)),
                ("is_debt", models.BooleanField(default=False)),
                ("debt_amount", models.IntegerField(default=0)),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.TimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=30)),
                ("amount", models.IntegerField()),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Incomings",
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.TimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("entry", models.JSONField()),
                ("submitted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "The Register",
                "verbose_name_plural": "Registries",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("level", models.JSONField()),
                (
                    "lessons_remaining_grammar_only",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "lessons_remaining_native_only",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "lessons_remaining",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("created", models.TimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("day", models.IntegerField(max_length=1)),
                ("time", models.TimeField()),
                (
                    "subject",
                    models.CharField(
                        choices=[("n", "native"), ("g", "grammar")], max_length=7
                    ),
                ),
                ("isonline", models.BooleanField(default=False)),
                ("created", models.TimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
    ]
