# Generated by Django 4.1.1 on 2023-09-06 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CuttingBatch",
            new_name="CuttingsBatch",
        ),
        migrations.AlterModelOptions(
            name="cuttingsbatch",
            options={
                "verbose_name": "Cuttings Batch",
                "verbose_name_plural": "Cuttings",
            },
        ),
        migrations.AddField(
            model_name="income",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
