# Generated by Django 4.1.1 on 2023-09-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_cuttingbatch_cuttingsbatch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="day",
            field=models.IntegerField(),
        ),
    ]
