# Generated by Django 4.1.1 on 2023-08-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_student_id_alter_student_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
