# Generated by Django 4.1.1 on 2023-09-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_lesson_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="level",
        ),
    ]
