# Generated by Django 4.1.1 on 2023-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_student_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="day",
            field=models.CharField(max_length=10),
        ),
    ]
