# Generated by Django 4.1.1 on 2023-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_lesson_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
