# Generated by Django 4.1.1 on 2023-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_expense_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("hm", "home"),
                    ("tr", "travel"),
                    ("fd", "food"),
                    ("bl", "bills"),
                    ("db", "debt"),
                    ("cr", "car"),
                    ("dg", "dogs"),
                    ("wf", "wife"),
                    ("hs", "husband"),
                    ("sc", "social tax"),
                    ("tl", "tutorland"),
                    ("cj", "cjgrower"),
                    ("ms", "misc"),
                ],
                max_length=2,
            ),
        ),
    ]
