# Generated by Django 4.1.1 on 2023-08-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finass", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpenseRecord",
        ),
        migrations.DeleteModel(
            name="RecordsBackup",
        ),
    ]
